[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_URL = "https://167.71.17.59"

[context.production.environment]
  VITE_API_URL = "https://167.71.17.59"